/**
 * This file implements a catch-all route that renders the user-facing pages
 * generated by Puck. For any route visited (with exception of other hardcoded
 * pages in /app), it will check your database (via `getPage`) for a Puck page
 * and render it using <Render>.
 *
 * All routes produced by this page are statically rendered using incremental
 * static site generation. After the first visit, the page will be cached as
 * a static file. Subsequent visits will receive the cache. Publishing a page
 * will invalidate the cache as the page is written in /api/puck/route.ts
 */

import { Client } from "./client";
import { notFound } from "next/navigation";
import { Metadata } from "next";
import { Data } from "@puckeditor/core";
import {
  getCollectionByHandle,
  medusaCollectionRepository,
} from "@/lib/repositories/medusa-collection-repository";
import { getPage } from "@/lib/get-page";
import { getProductTypesList } from "@/lib/repositories/product-types";
import { medusaCategoryRepository } from "@/lib/repositories/medusa-category-repository";
import { listProductsByCollection } from "@/lib/repositories/products";

export async function generateMetadata(): Promise<Metadata> {
  const path = `/home`;
  const data = await getPage(path);

  return {
    title: data?.root.props?.title,
  };
}

export default async function Page() {
  const path = `/home`;
  const data = await getPage(path);
  if (!data) {
    return notFound();
  }

  async function enrichData(
    item: Data["content"][number],
  ): Promise<Data["content"][number]> {
    const collections = await medusaCollectionRepository.list();
    const categories = await medusaCategoryRepository.list();

    switch (item.type) {
      case "CollectionProductsSliderSection":
        const collection = await listProductsByCollection(
          item.props.collection.handle,
        );

        if (!collection.items.length) return item;

        return {
          ...item,
          props: {
            ...item.props,
            data: collection.items,
          },
        };

      case "IncredibleOffersSection":
        const incredibleOffersCollection =
          await listProductsByCollection("incredible_offers");
        if (!incredibleOffersCollection.items.length) return item;
        return {
          ...item,
          props: {
            ...item.props,
            data: incredibleOffersCollection.items,
          },
        };

      case "CollectionsSectionWrapper":
        return {
          ...item,
          props: {
            ...item.props,
            data: collections.filter(
              (c) => c.handle !== "incredible_offers",
            ), // 👈 Live data
          },
        };

      case "CategoriesSlider":
        if(categories.length < 5) return item

        return {
          ...item,
          props: {
            ...item.props,
            data: categories
          },
        };

      // case "ProductTypesSection":
      //   return {
      //     ...item,
      //     props: {
      //       ...item.props,
      //       productTypes: productTypes?.productTypes, // 👈 Live data
      //     },
      //   };

      default:
        return item;
    }
  }

  const pageData: Data = {
    ...data,
    content: await Promise.all(data.content.map(enrichData)),
  };

  console.log(pageData);

  return <Client data={pageData} path={path} />;
}
