/**
 * This file implements a catch-all route that renders the user-facing pages
 * generated by Puck. For any route visited (with exception of other hardcoded
 * pages in /app), it will check your database (via `getPage`) for a Puck page
 * and render it using <Render>.
 *
 * All routes produced by this page are statically rendered using incremental
 * static site generation. After the first visit, the page will be cached as
 * a static file. Subsequent visits will receive the cache. Publishing a page
 * will invalidate the cache as the page is written in /api/puck/route.ts
 */

import { Client } from "./client";
import { notFound } from "next/navigation";
import { Metadata } from "next";
import { Data } from "@puckeditor/core";
import {
  getCollectionByHandle,
  medusaCollectionRepository,
} from "@/lib/repositories/medusa-collection-repository";
import { getPage } from "@/lib/get-page";
import { getProductTypesList } from "@/lib/repositories/product-types";

export async function generateMetadata(): Promise<Metadata> {
  const path = `/home`;
  const data = await getPage(path);

  return {
    title: data?.root.props?.title,
  };
}

export default async function Page() {
  const path = `/home`;
  const data = await getPage(path);
  if (!data) {
    return notFound();
  }

  // const productTypes = await getProductTypesList(0, 20, [
  //   "id",
  //   "value",
  //   "metadata",
  // ]);

  //   if (!productTypes) {
  //   return null;
  // }

  const collections = await medusaCollectionRepository.list();

  const incredibleOffersCollection = await getCollectionByHandle(
    process.env.NEXT_PUBLIC_INCREDIBLE_OFFER_HANDLE || "incredible_offers",
    ["id", "metadata", "products"],
  );

  const pageData: Data = {
    ...data,
    content: data.content.map((item: Data["content"][number]) => {
      // if (item.type === "ProductTypesSection" && productTypes) {
      //   return {
      //     ...item,
      //     props: {
      //       ...item.props,
      //       productTypes: productTypes?.productTypes, // 👈 Live data
      //     },
      //   };
      // }
      if (item.type === "CollectionsSectionWrapper" && collections) {
        return {
          ...item,
          props: {
            ...item.props,
            collections: collections.filter(
              (c) => c.handle !== "incredible_offers",
            ), // 👈 Live data
          },
        };
      }
      if (item.type === "IncredibleOffersSection" && incredibleOffersCollection) {
        return {
          ...item,
          props: {
            ...item.props,
            data: incredibleOffersCollection?.products, // 👈 Live data
          },
        };
      }
      return item;
    }),
  };

  return <Client data={data} path={path} />;
}
