//////////////////////////////////////////////////////////////////////////////////////////////
// DO NOT MODIFY THIS FILE                                                                  //
// This file is automatically generated by ZenStack CLI and should not be manually updated. //
//////////////////////////////////////////////////////////////////////////////////////////////

/* eslint-disable */

import { schema as $schema, type SchemaType as $Schema } from "./schema";
import type { ModelResult as $ModelResult, TypeDefResult as $TypeDefResult } from "@zenstackhq/orm";
export type StoreConfig = $ModelResult<$Schema, "StoreConfig">;
/**
 * A composable page (home, landing, campaign). Ordered list of sections.
 */
export type PageLayout = $ModelResult<$Schema, "PageLayout">;
/**
 * One block on a page. `config` is validated by a Zod schema keyed on `type`.
 */
export type Section = $ModelResult<$Schema, "Section">;
export type NavMenu = $ModelResult<$Schema, "NavMenu">;
export type NavItem = $ModelResult<$Schema, "NavItem">;
export type Popup = $ModelResult<$Schema, "Popup">;
/**
 * A scheduled content/promo "run".
 */
export type Campaign = $ModelResult<$Schema, "Campaign">;
export type GuestLead = $ModelResult<$Schema, "GuestLead">;
export type MediaAsset = $ModelResult<$Schema, "MediaAsset">;
/**
 * A product image feature vector for visual-similarity search. Vectors are
 * computed locally (sharp) and ranked by cosine similarity in the app.
 */
export type ProductEmbedding = $ModelResult<$Schema, "ProductEmbedding">;
/**
 * Customer product reviews (rating + text), keyed by the Medusa product handle.
 */
export type ProductReview = $ModelResult<$Schema, "ProductReview">;
/**
 * Phone OTP challenges (passwordless capture + registration phone verify).
 */
export type OtpChallenge = $ModelResult<$Schema, "OtpChallenge">;
/**
 * Singleton-style key→JSON store for editable site settings (announcement,
 * marquee, brand names, persona builder, delivery line, etc.).
 */
export type SiteSetting = $ModelResult<$Schema, "SiteSetting">;
export type Auth = $TypeDefResult<$Schema, "Auth">;
export type SeoRobots = $TypeDefResult<$Schema, "SeoRobots">;
export type SeoOpenGraph = $TypeDefResult<$Schema, "SeoOpenGraph">;
export type SeoTwitter = $TypeDefResult<$Schema, "SeoTwitter">;
export type StoreSeoConfig = $TypeDefResult<$Schema, "StoreSeoConfig">;
export type StoreSocialLinks = $TypeDefResult<$Schema, "StoreSocialLinks">;
export type StoreMarketingConfig = $TypeDefResult<$Schema, "StoreMarketingConfig">;
export const SubscriptionStatus = $schema.enums.SubscriptionStatus.values;
export type SubscriptionStatus = (typeof SubscriptionStatus)[keyof typeof SubscriptionStatus];
export const SectionType = $schema.enums.SectionType.values;
export type SectionType = (typeof SectionType)[keyof typeof SectionType];
export const PopupTrigger = $schema.enums.PopupTrigger.values;
export type PopupTrigger = (typeof PopupTrigger)[keyof typeof PopupTrigger];
export const CampaignStatus = $schema.enums.CampaignStatus.values;
export type CampaignStatus = (typeof CampaignStatus)[keyof typeof CampaignStatus];
export const MediaType = $schema.enums.MediaType.values;
export type MediaType = (typeof MediaType)[keyof typeof MediaType];
export const Status = $schema.enums.Status.values;
export type Status = (typeof Status)[keyof typeof Status];
