//////////////////////////////////////////////////////////////////////////////////////////////
// DO NOT MODIFY THIS FILE                                                                  //
// This file is automatically generated by ZenStack CLI and should not be manually updated. //
//////////////////////////////////////////////////////////////////////////////////////////////

/* eslint-disable */

import { type SchemaDef, type AttributeApplication, type FieldDefault, ExpressionUtils } from "@zenstackhq/schema";
export class SchemaType implements SchemaDef {
    provider = {
        type: "postgresql"
    } as const;
    models = {
        StoreConfig: {
            name: "StoreConfig",
            fields: {
                id: {
                    name: "id",
                    type: "String",
                    id: true,
                    attributes: [{ name: "@id" }, { name: "@default", args: [{ name: "value", value: ExpressionUtils.call("cuid") }] }] as readonly AttributeApplication[],
                    default: ExpressionUtils.call("cuid") as FieldDefault
                },
                createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.call("now") }] }] as readonly AttributeApplication[],
                    default: ExpressionUtils.call("now") as FieldDefault
                },
                updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    updatedAt: true,
                    attributes: [{ name: "@updatedAt" }] as readonly AttributeApplication[]
                },
                medusaStoreId: {
                    name: "medusaStoreId",
                    type: "String",
                    attributes: [{ name: "@map", args: [{ name: "name", value: ExpressionUtils.literal("medusa_store_id") }] }] as readonly AttributeApplication[]
                },
                title: {
                    name: "title",
                    type: "String",
                    optional: true
                },
                handle: {
                    name: "handle",
                    type: "String",
                    unique: true,
                    optional: true,
                    attributes: [{ name: "@unique" }] as readonly AttributeApplication[]
                },
                domain: {
                    name: "domain",
                    type: "String",
                    optional: true
                },
                description: {
                    name: "description",
                    type: "String",
                    optional: true,
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.literal("") }] }] as readonly AttributeApplication[],
                    default: "" as FieldDefault
                },
                logoUrl: {
                    name: "logoUrl",
                    type: "String",
                    optional: true,
                    attributes: [{ name: "@map", args: [{ name: "name", value: ExpressionUtils.literal("logo_url") }] }, { name: "@url" }] as readonly AttributeApplication[]
                },
                logoAlt: {
                    name: "logoAlt",
                    type: "String",
                    optional: true,
                    attributes: [{ name: "@map", args: [{ name: "name", value: ExpressionUtils.literal("logo_alt") }] }] as readonly AttributeApplication[]
                },
                faviconUrl: {
                    name: "faviconUrl",
                    type: "String",
                    optional: true,
                    attributes: [{ name: "@map", args: [{ name: "name", value: ExpressionUtils.literal("favicon_url") }] }, { name: "@url" }] as readonly AttributeApplication[]
                },
                theme: {
                    name: "theme",
                    type: "String",
                    optional: true,
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.literal("default") }] }] as readonly AttributeApplication[],
                    default: "default" as FieldDefault
                },
                themeOverrides: {
                    name: "themeOverrides",
                    type: "Json",
                    optional: true,
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.literal("{}") }] }, { name: "@map", args: [{ name: "name", value: ExpressionUtils.literal("theme_overrides") }] }] as readonly AttributeApplication[],
                    default: "{}" as FieldDefault
                },
                homepageLayout: {
                    name: "homepageLayout",
                    type: "Json",
                    optional: true,
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.literal("{}") }] }, { name: "@map", args: [{ name: "name", value: ExpressionUtils.literal("homepage_layout") }] }] as readonly AttributeApplication[],
                    default: "{}" as FieldDefault
                },
                aboutPageLayout: {
                    name: "aboutPageLayout",
                    type: "Json",
                    optional: true,
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.literal("{}") }] }, { name: "@map", args: [{ name: "name", value: ExpressionUtils.literal("about_page_layout") }] }] as readonly AttributeApplication[],
                    default: "{}" as FieldDefault
                },
                seoConfig: {
                    name: "seoConfig",
                    type: "Json",
                    optional: true,
                    attributes: [{ name: "@map", args: [{ name: "name", value: ExpressionUtils.literal("seo_config") }] }] as readonly AttributeApplication[]
                },
                marketingConfig: {
                    name: "marketingConfig",
                    type: "Json",
                    optional: true,
                    attributes: [{ name: "@map", args: [{ name: "name", value: ExpressionUtils.literal("marketing_config") }] }] as readonly AttributeApplication[]
                },
                config: {
                    name: "config",
                    type: "Json",
                    optional: true,
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.literal("{}") }] }] as readonly AttributeApplication[],
                    default: "{}" as FieldDefault
                },
                paymentConfigs: {
                    name: "paymentConfigs",
                    type: "Json",
                    optional: true,
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.literal("{}") }] }, { name: "@map", args: [{ name: "name", value: ExpressionUtils.literal("payment_configs") }] }] as readonly AttributeApplication[],
                    default: "{}" as FieldDefault
                },
                shippingMethodConfigs: {
                    name: "shippingMethodConfigs",
                    type: "Json",
                    optional: true,
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.literal("{}") }] }, { name: "@map", args: [{ name: "name", value: ExpressionUtils.literal("shipping_method_configs") }] }] as readonly AttributeApplication[],
                    default: "{}" as FieldDefault
                },
                subscriptionProductId: {
                    name: "subscriptionProductId",
                    type: "String",
                    unique: true,
                    optional: true,
                    attributes: [{ name: "@unique" }, { name: "@map", args: [{ name: "name", value: ExpressionUtils.literal("subscription_product_id") }] }] as readonly AttributeApplication[]
                },
                subscriptionStatus: {
                    name: "subscriptionStatus",
                    type: "SubscriptionStatus",
                    optional: true,
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.literal("PENDING") }] }, { name: "@map", args: [{ name: "name", value: ExpressionUtils.literal("subscription_status") }] }] as readonly AttributeApplication[],
                    default: "PENDING" as FieldDefault
                }
            },
            attributes: [
                { name: "@@allow", args: [{ name: "operation", value: ExpressionUtils.literal("all") }, { name: "condition", value: ExpressionUtils.binary(ExpressionUtils.member(ExpressionUtils.call("auth"), ["medusaStoreId"]), "==", ExpressionUtils.field("medusaStoreId")) }] },
                { name: "@@map", args: [{ name: "name", value: ExpressionUtils.literal("store_config") }] }
            ] as readonly AttributeApplication[],
            idFields: ["id"],
            uniqueFields: {
                id: { type: "String" },
                handle: { type: "String" },
                subscriptionProductId: { type: "String" }
            }
        },
        PageLayout: {
            name: "PageLayout",
            fields: {
                id: {
                    name: "id",
                    type: "String",
                    id: true,
                    attributes: [{ name: "@id" }, { name: "@default", args: [{ name: "value", value: ExpressionUtils.call("cuid") }] }] as readonly AttributeApplication[],
                    default: ExpressionUtils.call("cuid") as FieldDefault
                },
                slug: {
                    name: "slug",
                    type: "String",
                    unique: true,
                    attributes: [{ name: "@unique" }] as readonly AttributeApplication[]
                },
                title: {
                    name: "title",
                    type: "String"
                },
                status: {
                    name: "status",
                    type: "Status",
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.literal("DRAFT") }] }] as readonly AttributeApplication[],
                    default: "DRAFT" as FieldDefault
                },
                publishedAt: {
                    name: "publishedAt",
                    type: "DateTime",
                    optional: true
                },
                sections: {
                    name: "sections",
                    type: "Section",
                    array: true,
                    relation: { opposite: "pageLayout" }
                },
                createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.call("now") }] }] as readonly AttributeApplication[],
                    default: ExpressionUtils.call("now") as FieldDefault
                },
                updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    updatedAt: true,
                    attributes: [{ name: "@updatedAt" }] as readonly AttributeApplication[]
                }
            },
            idFields: ["id"],
            uniqueFields: {
                id: { type: "String" },
                slug: { type: "String" }
            }
        },
        Section: {
            name: "Section",
            fields: {
                id: {
                    name: "id",
                    type: "String",
                    id: true,
                    attributes: [{ name: "@id" }, { name: "@default", args: [{ name: "value", value: ExpressionUtils.call("cuid") }] }] as readonly AttributeApplication[],
                    default: ExpressionUtils.call("cuid") as FieldDefault
                },
                type: {
                    name: "type",
                    type: "SectionType"
                },
                position: {
                    name: "position",
                    type: "Int",
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.literal(0) }] }] as readonly AttributeApplication[],
                    default: 0 as FieldDefault
                },
                config: {
                    name: "config",
                    type: "Json",
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.literal("{}") }] }] as readonly AttributeApplication[],
                    default: "{}" as FieldDefault
                },
                pageLayout: {
                    name: "pageLayout",
                    type: "PageLayout",
                    attributes: [{ name: "@relation", args: [{ name: "fields", value: ExpressionUtils.array("String", [ExpressionUtils.field("pageLayoutId")]) }, { name: "references", value: ExpressionUtils.array("String", [ExpressionUtils.field("id")]) }, { name: "onDelete", value: ExpressionUtils.literal("Cascade") }] }] as readonly AttributeApplication[],
                    relation: { opposite: "sections", fields: ["pageLayoutId"], references: ["id"], onDelete: "Cascade" }
                },
                pageLayoutId: {
                    name: "pageLayoutId",
                    type: "String",
                    foreignKeyFor: [
                        "pageLayout"
                    ] as readonly string[]
                },
                createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.call("now") }] }] as readonly AttributeApplication[],
                    default: ExpressionUtils.call("now") as FieldDefault
                },
                updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    updatedAt: true,
                    attributes: [{ name: "@updatedAt" }] as readonly AttributeApplication[]
                }
            },
            attributes: [
                { name: "@@index", args: [{ name: "fields", value: ExpressionUtils.array("String", [ExpressionUtils.field("pageLayoutId"), ExpressionUtils.field("position")]) }] }
            ] as readonly AttributeApplication[],
            idFields: ["id"],
            uniqueFields: {
                id: { type: "String" }
            }
        },
        NavMenu: {
            name: "NavMenu",
            fields: {
                id: {
                    name: "id",
                    type: "String",
                    id: true,
                    attributes: [{ name: "@id" }, { name: "@default", args: [{ name: "value", value: ExpressionUtils.call("cuid") }] }] as readonly AttributeApplication[],
                    default: ExpressionUtils.call("cuid") as FieldDefault
                },
                key: {
                    name: "key",
                    type: "String",
                    unique: true,
                    attributes: [{ name: "@unique" }] as readonly AttributeApplication[]
                },
                items: {
                    name: "items",
                    type: "NavItem",
                    array: true,
                    relation: { opposite: "menu" }
                },
                updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    updatedAt: true,
                    attributes: [{ name: "@updatedAt" }] as readonly AttributeApplication[]
                }
            },
            idFields: ["id"],
            uniqueFields: {
                id: { type: "String" },
                key: { type: "String" }
            }
        },
        NavItem: {
            name: "NavItem",
            fields: {
                id: {
                    name: "id",
                    type: "String",
                    id: true,
                    attributes: [{ name: "@id" }, { name: "@default", args: [{ name: "value", value: ExpressionUtils.call("cuid") }] }] as readonly AttributeApplication[],
                    default: ExpressionUtils.call("cuid") as FieldDefault
                },
                label: {
                    name: "label",
                    type: "String"
                },
                href: {
                    name: "href",
                    type: "String"
                },
                position: {
                    name: "position",
                    type: "Int",
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.literal(0) }] }] as readonly AttributeApplication[],
                    default: 0 as FieldDefault
                },
                megaMenu: {
                    name: "megaMenu",
                    type: "Json",
                    optional: true
                },
                menu: {
                    name: "menu",
                    type: "NavMenu",
                    attributes: [{ name: "@relation", args: [{ name: "fields", value: ExpressionUtils.array("String", [ExpressionUtils.field("menuId")]) }, { name: "references", value: ExpressionUtils.array("String", [ExpressionUtils.field("id")]) }, { name: "onDelete", value: ExpressionUtils.literal("Cascade") }] }] as readonly AttributeApplication[],
                    relation: { opposite: "items", fields: ["menuId"], references: ["id"], onDelete: "Cascade" }
                },
                menuId: {
                    name: "menuId",
                    type: "String",
                    foreignKeyFor: [
                        "menu"
                    ] as readonly string[]
                },
                parent: {
                    name: "parent",
                    type: "NavItem",
                    optional: true,
                    attributes: [{ name: "@relation", args: [{ name: "name", value: ExpressionUtils.literal("NavChildren") }, { name: "fields", value: ExpressionUtils.array("String", [ExpressionUtils.field("parentId")]) }, { name: "references", value: ExpressionUtils.array("String", [ExpressionUtils.field("id")]) }, { name: "onDelete", value: ExpressionUtils.literal("Cascade") }] }] as readonly AttributeApplication[],
                    relation: { opposite: "children", name: "NavChildren", fields: ["parentId"], references: ["id"], onDelete: "Cascade" }
                },
                parentId: {
                    name: "parentId",
                    type: "String",
                    optional: true,
                    foreignKeyFor: [
                        "parent"
                    ] as readonly string[]
                },
                children: {
                    name: "children",
                    type: "NavItem",
                    array: true,
                    attributes: [{ name: "@relation", args: [{ name: "name", value: ExpressionUtils.literal("NavChildren") }] }] as readonly AttributeApplication[],
                    relation: { opposite: "parent", name: "NavChildren" }
                }
            },
            attributes: [
                { name: "@@index", args: [{ name: "fields", value: ExpressionUtils.array("String", [ExpressionUtils.field("menuId"), ExpressionUtils.field("position")]) }] }
            ] as readonly AttributeApplication[],
            idFields: ["id"],
            uniqueFields: {
                id: { type: "String" }
            }
        },
        Popup: {
            name: "Popup",
            fields: {
                id: {
                    name: "id",
                    type: "String",
                    id: true,
                    attributes: [{ name: "@id" }, { name: "@default", args: [{ name: "value", value: ExpressionUtils.call("cuid") }] }] as readonly AttributeApplication[],
                    default: ExpressionUtils.call("cuid") as FieldDefault
                },
                name: {
                    name: "name",
                    type: "String"
                },
                active: {
                    name: "active",
                    type: "Boolean",
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.literal(false) }] }] as readonly AttributeApplication[],
                    default: false as FieldDefault
                },
                trigger: {
                    name: "trigger",
                    type: "PopupTrigger",
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.literal("TIMER") }] }] as readonly AttributeApplication[],
                    default: "TIMER" as FieldDefault
                },
                config: {
                    name: "config",
                    type: "Json",
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.literal("{}") }] }] as readonly AttributeApplication[],
                    default: "{}" as FieldDefault
                },
                startsAt: {
                    name: "startsAt",
                    type: "DateTime",
                    optional: true
                },
                endsAt: {
                    name: "endsAt",
                    type: "DateTime",
                    optional: true
                },
                createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.call("now") }] }] as readonly AttributeApplication[],
                    default: ExpressionUtils.call("now") as FieldDefault
                },
                updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    updatedAt: true,
                    attributes: [{ name: "@updatedAt" }] as readonly AttributeApplication[]
                }
            },
            idFields: ["id"],
            uniqueFields: {
                id: { type: "String" }
            }
        },
        Campaign: {
            name: "Campaign",
            fields: {
                id: {
                    name: "id",
                    type: "String",
                    id: true,
                    attributes: [{ name: "@id" }, { name: "@default", args: [{ name: "value", value: ExpressionUtils.call("cuid") }] }] as readonly AttributeApplication[],
                    default: ExpressionUtils.call("cuid") as FieldDefault
                },
                name: {
                    name: "name",
                    type: "String"
                },
                status: {
                    name: "status",
                    type: "CampaignStatus",
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.literal("SCHEDULED") }] }] as readonly AttributeApplication[],
                    default: "SCHEDULED" as FieldDefault
                },
                startsAt: {
                    name: "startsAt",
                    type: "DateTime"
                },
                endsAt: {
                    name: "endsAt",
                    type: "DateTime",
                    optional: true
                },
                payload: {
                    name: "payload",
                    type: "Json",
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.literal("{}") }] }] as readonly AttributeApplication[],
                    default: "{}" as FieldDefault
                },
                createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.call("now") }] }] as readonly AttributeApplication[],
                    default: ExpressionUtils.call("now") as FieldDefault
                },
                updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    updatedAt: true,
                    attributes: [{ name: "@updatedAt" }] as readonly AttributeApplication[]
                }
            },
            attributes: [
                { name: "@@index", args: [{ name: "fields", value: ExpressionUtils.array("CampaignStatus", [ExpressionUtils.field("status"), ExpressionUtils.field("startsAt")]) }] }
            ] as readonly AttributeApplication[],
            idFields: ["id"],
            uniqueFields: {
                id: { type: "String" }
            }
        },
        GuestLead: {
            name: "GuestLead",
            fields: {
                id: {
                    name: "id",
                    type: "String",
                    id: true,
                    attributes: [{ name: "@id" }, { name: "@default", args: [{ name: "value", value: ExpressionUtils.call("cuid") }] }] as readonly AttributeApplication[],
                    default: ExpressionUtils.call("cuid") as FieldDefault
                },
                email: {
                    name: "email",
                    type: "String",
                    optional: true
                },
                phone: {
                    name: "phone",
                    type: "String",
                    optional: true
                },
                capturedFields: {
                    name: "capturedFields",
                    type: "Json",
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.literal("{}") }] }] as readonly AttributeApplication[],
                    default: "{}" as FieldDefault
                },
                cartId: {
                    name: "cartId",
                    type: "String",
                    optional: true
                },
                source: {
                    name: "source",
                    type: "String",
                    optional: true
                },
                createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.call("now") }] }] as readonly AttributeApplication[],
                    default: ExpressionUtils.call("now") as FieldDefault
                },
                updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    updatedAt: true,
                    attributes: [{ name: "@updatedAt" }] as readonly AttributeApplication[]
                }
            },
            attributes: [
                { name: "@@index", args: [{ name: "fields", value: ExpressionUtils.array("String", [ExpressionUtils.field("email")]) }] },
                { name: "@@index", args: [{ name: "fields", value: ExpressionUtils.array("String", [ExpressionUtils.field("cartId")]) }] }
            ] as readonly AttributeApplication[],
            idFields: ["id"],
            uniqueFields: {
                id: { type: "String" }
            }
        },
        MediaAsset: {
            name: "MediaAsset",
            fields: {
                id: {
                    name: "id",
                    type: "String",
                    id: true,
                    attributes: [{ name: "@id" }, { name: "@default", args: [{ name: "value", value: ExpressionUtils.call("cuid") }] }] as readonly AttributeApplication[],
                    default: ExpressionUtils.call("cuid") as FieldDefault
                },
                url: {
                    name: "url",
                    type: "String"
                },
                type: {
                    name: "type",
                    type: "MediaType",
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.literal("IMAGE") }] }] as readonly AttributeApplication[],
                    default: "IMAGE" as FieldDefault
                },
                alt: {
                    name: "alt",
                    type: "String",
                    optional: true
                },
                width: {
                    name: "width",
                    type: "Int",
                    optional: true
                },
                height: {
                    name: "height",
                    type: "Int",
                    optional: true
                },
                focal: {
                    name: "focal",
                    type: "Json",
                    optional: true
                },
                createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.call("now") }] }] as readonly AttributeApplication[],
                    default: ExpressionUtils.call("now") as FieldDefault
                }
            },
            idFields: ["id"],
            uniqueFields: {
                id: { type: "String" }
            }
        },
        ProductEmbedding: {
            name: "ProductEmbedding",
            fields: {
                id: {
                    name: "id",
                    type: "String",
                    id: true,
                    attributes: [{ name: "@id" }, { name: "@default", args: [{ name: "value", value: ExpressionUtils.call("cuid") }] }] as readonly AttributeApplication[],
                    default: ExpressionUtils.call("cuid") as FieldDefault
                },
                productId: {
                    name: "productId",
                    type: "String",
                    unique: true,
                    attributes: [{ name: "@unique" }] as readonly AttributeApplication[]
                },
                handle: {
                    name: "handle",
                    type: "String"
                },
                title: {
                    name: "title",
                    type: "String"
                },
                thumbnail: {
                    name: "thumbnail",
                    type: "String"
                },
                price: {
                    name: "price",
                    type: "String"
                },
                dim: {
                    name: "dim",
                    type: "Int"
                },
                vector: {
                    name: "vector",
                    type: "Float",
                    array: true
                },
                updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    updatedAt: true,
                    attributes: [{ name: "@updatedAt" }] as readonly AttributeApplication[]
                }
            },
            idFields: ["id"],
            uniqueFields: {
                id: { type: "String" },
                productId: { type: "String" }
            }
        },
        ProductReview: {
            name: "ProductReview",
            fields: {
                id: {
                    name: "id",
                    type: "String",
                    id: true,
                    attributes: [{ name: "@id" }, { name: "@default", args: [{ name: "value", value: ExpressionUtils.call("cuid") }] }] as readonly AttributeApplication[],
                    default: ExpressionUtils.call("cuid") as FieldDefault
                },
                productHandle: {
                    name: "productHandle",
                    type: "String"
                },
                rating: {
                    name: "rating",
                    type: "Int"
                },
                author: {
                    name: "author",
                    type: "String"
                },
                title: {
                    name: "title",
                    type: "String",
                    optional: true
                },
                body: {
                    name: "body",
                    type: "String"
                },
                approved: {
                    name: "approved",
                    type: "Boolean",
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.literal(true) }] }] as readonly AttributeApplication[],
                    default: true as FieldDefault
                },
                createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.call("now") }] }] as readonly AttributeApplication[],
                    default: ExpressionUtils.call("now") as FieldDefault
                }
            },
            attributes: [
                { name: "@@index", args: [{ name: "fields", value: ExpressionUtils.array("String", [ExpressionUtils.field("productHandle"), ExpressionUtils.field("createdAt")]) }] }
            ] as readonly AttributeApplication[],
            idFields: ["id"],
            uniqueFields: {
                id: { type: "String" }
            }
        },
        OtpChallenge: {
            name: "OtpChallenge",
            fields: {
                id: {
                    name: "id",
                    type: "String",
                    id: true,
                    attributes: [{ name: "@id" }, { name: "@default", args: [{ name: "value", value: ExpressionUtils.call("cuid") }] }] as readonly AttributeApplication[],
                    default: ExpressionUtils.call("cuid") as FieldDefault
                },
                phone: {
                    name: "phone",
                    type: "String"
                },
                code: {
                    name: "code",
                    type: "String"
                },
                expiresAt: {
                    name: "expiresAt",
                    type: "DateTime"
                },
                attempts: {
                    name: "attempts",
                    type: "Int",
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.literal(0) }] }] as readonly AttributeApplication[],
                    default: 0 as FieldDefault
                },
                verified: {
                    name: "verified",
                    type: "Boolean",
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.literal(false) }] }] as readonly AttributeApplication[],
                    default: false as FieldDefault
                },
                createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.call("now") }] }] as readonly AttributeApplication[],
                    default: ExpressionUtils.call("now") as FieldDefault
                }
            },
            attributes: [
                { name: "@@index", args: [{ name: "fields", value: ExpressionUtils.array("String", [ExpressionUtils.field("phone")]) }] }
            ] as readonly AttributeApplication[],
            idFields: ["id"],
            uniqueFields: {
                id: { type: "String" }
            }
        },
        SiteSetting: {
            name: "SiteSetting",
            fields: {
                key: {
                    name: "key",
                    type: "String",
                    id: true,
                    attributes: [{ name: "@id" }] as readonly AttributeApplication[]
                },
                value: {
                    name: "value",
                    type: "Json",
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.literal("{}") }] }] as readonly AttributeApplication[],
                    default: "{}" as FieldDefault
                },
                updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    updatedAt: true,
                    attributes: [{ name: "@updatedAt" }] as readonly AttributeApplication[]
                }
            },
            idFields: ["key"],
            uniqueFields: {
                key: { type: "String" }
            }
        }
    } as const;
    typeDefs = {
        Auth: {
            name: "Auth",
            fields: {
                medusaStoreId: {
                    name: "medusaStoreId",
                    type: "String",
                    attributes: [{ name: "@id" }] as readonly AttributeApplication[]
                }
            },
            attributes: [
                { name: "@@auth" }
            ] as readonly AttributeApplication[]
        },
        SeoRobots: {
            name: "SeoRobots",
            fields: {
                index: {
                    name: "index",
                    type: "Boolean",
                    optional: true
                },
                follow: {
                    name: "follow",
                    type: "Boolean",
                    optional: true
                }
            }
        },
        SeoOpenGraph: {
            name: "SeoOpenGraph",
            fields: {
                site_name: {
                    name: "site_name",
                    type: "String",
                    optional: true
                },
                type: {
                    name: "type",
                    type: "String",
                    optional: true
                },
                image_url: {
                    name: "image_url",
                    type: "String",
                    optional: true,
                    attributes: [{ name: "@url" }] as readonly AttributeApplication[]
                }
            }
        },
        SeoTwitter: {
            name: "SeoTwitter",
            fields: {
                card: {
                    name: "card",
                    type: "String",
                    optional: true
                },
                site: {
                    name: "site",
                    type: "String",
                    optional: true
                }
            }
        },
        StoreSeoConfig: {
            name: "StoreSeoConfig",
            fields: {
                title_template: {
                    name: "title_template",
                    type: "String",
                    optional: true
                },
                default_title: {
                    name: "default_title",
                    type: "String",
                    optional: true
                },
                default_description: {
                    name: "default_description",
                    type: "String",
                    optional: true
                },
                default_image_url: {
                    name: "default_image_url",
                    type: "String",
                    optional: true,
                    attributes: [{ name: "@url" }] as readonly AttributeApplication[]
                },
                canonical_url: {
                    name: "canonical_url",
                    type: "String",
                    optional: true,
                    attributes: [{ name: "@url" }] as readonly AttributeApplication[]
                },
                robots: {
                    name: "robots",
                    type: "SeoRobots",
                    optional: true,
                    attributes: [{ name: "@json" }] as readonly AttributeApplication[]
                },
                open_graph: {
                    name: "open_graph",
                    type: "SeoOpenGraph",
                    optional: true,
                    attributes: [{ name: "@json" }] as readonly AttributeApplication[]
                },
                twitter: {
                    name: "twitter",
                    type: "SeoTwitter",
                    optional: true,
                    attributes: [{ name: "@json" }] as readonly AttributeApplication[]
                }
            }
        },
        StoreSocialLinks: {
            name: "StoreSocialLinks",
            fields: {
                instagram: {
                    name: "instagram",
                    type: "String",
                    optional: true,
                    attributes: [{ name: "@url" }] as readonly AttributeApplication[]
                },
                x: {
                    name: "x",
                    type: "String",
                    optional: true,
                    attributes: [{ name: "@url" }] as readonly AttributeApplication[]
                },
                facebook: {
                    name: "facebook",
                    type: "String",
                    optional: true,
                    attributes: [{ name: "@url" }] as readonly AttributeApplication[]
                },
                linkedin: {
                    name: "linkedin",
                    type: "String",
                    optional: true,
                    attributes: [{ name: "@url" }] as readonly AttributeApplication[]
                },
                youtube: {
                    name: "youtube",
                    type: "String",
                    optional: true,
                    attributes: [{ name: "@url" }] as readonly AttributeApplication[]
                },
                tiktok: {
                    name: "tiktok",
                    type: "String",
                    optional: true,
                    attributes: [{ name: "@url" }] as readonly AttributeApplication[]
                }
            }
        },
        StoreMarketingConfig: {
            name: "StoreMarketingConfig",
            fields: {
                google_analytics_id: {
                    name: "google_analytics_id",
                    type: "String",
                    optional: true
                },
                google_tag_manager_id: {
                    name: "google_tag_manager_id",
                    type: "String",
                    optional: true
                },
                meta_pixel_id: {
                    name: "meta_pixel_id",
                    type: "String",
                    optional: true
                },
                tiktok_pixel_id: {
                    name: "tiktok_pixel_id",
                    type: "String",
                    optional: true
                },
                newsletter_provider: {
                    name: "newsletter_provider",
                    type: "String",
                    optional: true
                },
                social_links: {
                    name: "social_links",
                    type: "StoreSocialLinks",
                    optional: true,
                    attributes: [{ name: "@json" }] as readonly AttributeApplication[]
                }
            }
        }
    } as const;
    enums = {
        SubscriptionStatus: {
            name: "SubscriptionStatus",
            values: {
                PENDING: "PENDING",
                ACTIVE: "ACTIVE",
                PAST_DUE: "PAST_DUE",
                CANCELED: "CANCELED",
                TRIALING: "TRIALING"
            }
        },
        SectionType: {
            name: "SectionType",
            values: {
                HERO: "HERO",
                PRODUCT_ROW: "PRODUCT_ROW",
                CATEGORY_GRID: "CATEGORY_GRID",
                EDITORIAL: "EDITORIAL",
                BANNER: "BANNER",
                MARQUEE: "MARQUEE"
            }
        },
        PopupTrigger: {
            name: "PopupTrigger",
            values: {
                TIMER: "TIMER",
                SCROLL: "SCROLL",
                EXIT_INTENT: "EXIT_INTENT",
                IMMEDIATE: "IMMEDIATE"
            }
        },
        CampaignStatus: {
            name: "CampaignStatus",
            values: {
                SCHEDULED: "SCHEDULED",
                ACTIVE: "ACTIVE",
                ENDED: "ENDED",
                PAUSED: "PAUSED"
            }
        },
        MediaType: {
            name: "MediaType",
            values: {
                IMAGE: "IMAGE",
                VIDEO: "VIDEO"
            }
        },
        Status: {
            name: "Status",
            values: {
                DRAFT: "DRAFT",
                PUBLISHED: "PUBLISHED",
                ARCHIVED: "ARCHIVED"
            }
        }
    } as const;
    authType = "Auth" as const;
    plugins = {};
}
export const schema = new SchemaType();
